"""Add metric2 to mat view

Revision ID: 07efb1bef54d
Revises: 7ea9419bdb87
Create Date: 2022-05-11 23:54:55.560466

"""
from alembic import op
import clickhouse_sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07efb1bef54d'
down_revision = '7ea9419bdb87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.detach_mat_view('grouped_statistics')
    op.add_column('.inner.grouped_statistics', sa.Column('metric2', clickhouse_sqlalchemy.types.common.Int32(), nullable=False, clickhouse_codec=('DoubleDelta', 'ZSTD')))
    op.attach_mat_view(
        'grouped_statistics',
        'SELECT statistics.date, sum(statistics.metric1 * statistics.sign) AS metric1 '
        'FROM statistics '
        'WHERE statistics.grouping > 42 GROUP BY statistics.date',
        'SummingMergeTree()'
        ' PARTITION BY toYYYYMM(date)'
        ' ORDER BY date',
        sa.Column('date', clickhouse_sqlalchemy.types.common.Date(), nullable=False),
        sa.Column('metric1', clickhouse_sqlalchemy.types.common.Int32(), nullable=False),
        sa.Column('metric2', clickhouse_sqlalchemy.types.common.Int32(), nullable=False, clickhouse_codec=('DoubleDelta', 'ZSTD'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.detach_mat_view('grouped_statistics')
    op.drop_column('.inner.grouped_statistics', 'metric2')
    op.attach_mat_view(
        'grouped_statistics',
        'SELECT statistics.date, sum(statistics.metric1 * statistics.sign) AS metric1 FROM alembic.statistics WHERE statistics.grouping > 42 GROUP BY statistics.date',
        'SummingMergeTree()'
        ' PARTITION BY toYYYYMM(date)'
        ' ORDER BY date',
        sa.Column('date', clickhouse_sqlalchemy.types.common.Date(), nullable=False),
        sa.Column('metric1', clickhouse_sqlalchemy.types.common.Int32(), nullable=False),
        sa.Column('metric2', clickhouse_sqlalchemy.types.common.Int32(), nullable=False, clickhouse_codec=('DoubleDelta', 'ZSTD'))
    )
    # ### end Alembic commands ###
