"""Init

Revision ID: ebd7d2403638
Revises: 
Create Date: 2022-05-11 22:55:18.701107

"""
from alembic import op
import clickhouse_sqlalchemy
from clickhouse_sqlalchemy import engines
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebd7d2403638'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('date', clickhouse_sqlalchemy.types.common.Date(), nullable=False),
    sa.Column('sign', clickhouse_sqlalchemy.types.common.Int8(), nullable=True),
    sa.Column('grouping', clickhouse_sqlalchemy.types.common.Int32(), nullable=True),
    sa.Column('metric1', clickhouse_sqlalchemy.types.common.Int32(), nullable=True),
    sa.PrimaryKeyConstraint('date'),
    engines.CollapsingMergeTree('sign', partition_by=sa.text('toYYYYMM(date)'), order_by=('date', 'grouping'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics')
    # ### end Alembic commands ###
